base:
    resource: .
    type: attribute
    prefix: /products

children:
    resource: './*/routes.yaml'
    prefix: /products

# Use below syntax for automapping entities to controller
#    defaults:
#        map:
#            App\Entity\TestLocation\TestLocation: 'location_id'
