twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'  # default for app
        #        - '@TbbcMoney/Form/fields.html.twig'
        - 'widgets.html.twig'
        - 'form_collection_widget.html.twig'

when@test:
    twig:
        strict_variables: true
