base:
    resource: .
    type: attribute
    prefix: /app

children:
    resource: './*/routes.yaml'
    prefix: /app

# Use below syntax for automapping entities to controller
#    defaults:
#        map:
#            Application\Entity\TestLocation\TestLocation: 'location_id'
